'use client';

import { useCallback } from 'react';

// Module-level so a new utterance/clip cancels the previous one (only one child
// session per tab).
let currentClip: HTMLAudioElement | null = null;

/**
 * ALL pre-generated MeloTTS clips are disabled — both single-character
 * (`audio/chars/{id}.mp3`) AND multi-syllable word (`audio/words/{id}.mp3`)
 * clips. MeloTTS Mandarin pronunciation is unreliable: wrong tones and wrong
 * polyphone (多音字) readings. In a tonal language a word on the wrong tone is a
 * DIFFERENT word — unacceptable for a learning app. We fall back to the device's
 * context-aware zh-CN voice, which is excellent on the target iPads AND is always
 * keyed to the correct `text` we pass (so it can never play "the wrong word").
 *
 * Char clips were disabled first (PR #120); word clips followed once David's
 * playtest found many word clips equally wrong. The clip data is preserved in
 * DB/Blob behind this flag — re-enable ONLY with a provider whose Mandarin tones
 * are verified correct, and prefer routing it through a NEW Blob path (e.g.
 * `audio/v2/…`) so the path-based filter below keeps the bad MeloTTS clips off.
 */
const USE_MELOTTS_CLIPS = false;

/** MeloTTS Blob paths whose audio is unreliable (see USE_MELOTTS_CLIPS). */
const MELOTTS_CLIP_PATH = /\/audio\/(chars|words)\//;

/**
 * Returns the clip URL to actually use, or null to fall back to the device voice.
 * The unreliable MeloTTS clips (chars + words) are filtered out unless
 * `USE_MELOTTS_CLIPS` is on; any other (future-provider) clip URL passes through.
 */
export function usableAudioUrl(audioUrl?: string | null): string | null {
  if (!audioUrl) return null;
  if (!USE_MELOTTS_CLIPS && MELOTTS_CLIP_PATH.test(audioUrl)) return null;
  return audioUrl;
}

function speakTts(text: string): void {
  const synth = window.speechSynthesis;
  if (synth == null) return;
  try {
    synth.cancel();
    const utt = new SpeechSynthesisUtterance(text);
    utt.lang = 'zh-CN';
    utt.rate = 0.85;
    synth.speak(utt);
  } catch (err) {
    console.warn('[useSpeak] tts failed:', err);
  }
}

/**
 * Speak a Chinese word/character. Prefers a **pre-recorded clip** (`audioUrl`,
 * generated by `scripts/generate-audio-cloudflare.ts` — consistent, high-quality
 * MeloTTS) when one exists; otherwise falls back to the browser's Web Speech
 * voice (quality varies by device). A clip that fails to play (autoplay block /
 * bad URL) also falls back to TTS.
 */
export function useSpeak(): (text: string, audioUrl?: string | null) => void {
  return useCallback((text: string, audioUrl?: string | null) => {
    if (typeof window === 'undefined') return;
    const url = usableAudioUrl(audioUrl);
    if (url) {
      try {
        window.speechSynthesis?.cancel();
        if (currentClip) {
          currentClip.pause();
          currentClip = null;
        }
        const clip = new Audio(url);
        currentClip = clip;
        void clip.play().catch(() => speakTts(text));
        return;
      } catch {
        // fall through to TTS
      }
    }
    speakTts(text);
  }, []);
}
