'use client';

import { useCallback } from 'react';

// Module-level so a new utterance/clip cancels the previous one (only one child
// session per tab).
let currentClip: HTMLAudioElement | null = null;

function speakTts(text: string): void {
  const synth = window.speechSynthesis;
  if (synth == null) return;
  try {
    synth.cancel();
    const utt = new SpeechSynthesisUtterance(text);
    utt.lang = 'zh-CN';
    utt.rate = 0.85;
    synth.speak(utt);
  } catch (err) {
    console.warn('[useSpeak] tts failed:', err);
  }
}

/**
 * Speak a Chinese word/character. Prefers a **pre-recorded clip** (`audioUrl`,
 * generated by `scripts/generate-audio-cloudflare.ts` — consistent, high-quality
 * MeloTTS) when one exists; otherwise falls back to the browser's Web Speech
 * voice (quality varies by device). A clip that fails to play (autoplay block /
 * bad URL) also falls back to TTS.
 */
export function useSpeak(): (text: string, audioUrl?: string | null) => void {
  return useCallback((text: string, audioUrl?: string | null) => {
    if (typeof window === 'undefined') return;
    if (audioUrl) {
      try {
        window.speechSynthesis?.cancel();
        if (currentClip) {
          currentClip.pause();
          currentClip = null;
        }
        const clip = new Audio(audioUrl);
        currentClip = clip;
        void clip.play().catch(() => speakTts(text));
        return;
      } catch {
        // fall through to TTS
      }
    }
    speakTts(text);
  }, []);
}
