/**
 * Source of truth for the 世界国旗 / World Flags collection pack.
 *
 * Yinuo is English-native (UK heritage learner) — every field that the kid
 * sees is bilingual. Capital is rendered alongside the country name; lore is
 * one short, kid-friendly fact per country. Emoji flags are stored in
 * `collectible_items.image_url` at seed time; the renderer uses them as plain
 * text glyphs (no `<img>`).
 */

export type FlagRarity = 'common' | 'rare' | 'epic';

export interface FlagItem {
  slug: string;
  emoji: string;
  nameZh: string;
  nameEn: string;
  capitalZh: string;
  capitalEn: string;
  loreZh: string;
  loreEn: string;
  rarity: FlagRarity;
  dropWeight: number;
}

export const FLAGS: FlagItem[] = [
  {
    slug: 'china',
    emoji: '🇨🇳',
    nameZh: '中国',
    nameEn: 'China',
    capitalZh: '北京',
    capitalEn: 'Beijing',
    loreZh: '大熊猫的故乡。',
    loreEn: 'Home of the giant panda!',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'uk',
    emoji: '🇬🇧',
    nameZh: '英国',
    nameEn: 'United Kingdom',
    capitalZh: '伦敦',
    capitalEn: 'London',
    loreZh: '有红色双层巴士。',
    loreEn: 'Famous for red double-decker buses.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'usa',
    emoji: '🇺🇸',
    nameZh: '美国',
    nameEn: 'United States',
    capitalZh: '华盛顿',
    capitalEn: 'Washington, D.C.',
    loreZh: '有五十颗星星的国旗。',
    loreEn: 'Its flag has fifty stars.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'france',
    emoji: '🇫🇷',
    nameZh: '法国',
    nameEn: 'France',
    capitalZh: '巴黎',
    capitalEn: 'Paris',
    loreZh: '有埃菲尔铁塔。',
    loreEn: 'Home of the Eiffel Tower.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'germany',
    emoji: '🇩🇪',
    nameZh: '德国',
    nameEn: 'Germany',
    capitalZh: '柏林',
    capitalEn: 'Berlin',
    loreZh: '香肠和面包很有名。',
    loreEn: 'Famous for sausages and bread.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'japan',
    emoji: '🇯🇵',
    nameZh: '日本',
    nameEn: 'Japan',
    capitalZh: '东京',
    capitalEn: 'Tokyo',
    loreZh: '樱花和富士山很美丽。',
    loreEn: 'Cherry blossoms and Mount Fuji!',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'south-korea',
    emoji: '🇰🇷',
    nameZh: '韩国',
    nameEn: 'South Korea',
    capitalZh: '首尔',
    capitalEn: 'Seoul',
    loreZh: '泡菜和歌曲很流行。',
    loreEn: 'Famous for kimchi and K-pop.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'canada',
    emoji: '🇨🇦',
    nameZh: '加拿大',
    nameEn: 'Canada',
    capitalZh: '渥太华',
    capitalEn: 'Ottawa',
    loreZh: '国旗上有一片枫叶。',
    loreEn: 'A maple leaf on the flag.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'australia',
    emoji: '🇦🇺',
    nameZh: '澳大利亚',
    nameEn: 'Australia',
    capitalZh: '堪培拉',
    capitalEn: 'Canberra',
    loreZh: '袋鼠和考拉的家。',
    loreEn: 'Home of kangaroos and koalas.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'india',
    emoji: '🇮🇳',
    nameZh: '印度',
    nameEn: 'India',
    capitalZh: '新德里',
    capitalEn: 'New Delhi',
    loreZh: '有美丽的泰姬陵。',
    loreEn: 'Home of the Taj Mahal.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'brazil',
    emoji: '🇧🇷',
    nameZh: '巴西',
    nameEn: 'Brazil',
    capitalZh: '巴西利亚',
    capitalEn: 'Brasília',
    loreZh: '亚马逊雨林在这里。',
    loreEn: 'Home of the Amazon rainforest.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'russia',
    emoji: '🇷🇺',
    nameZh: '俄罗斯',
    nameEn: 'Russia',
    capitalZh: '莫斯科',
    capitalEn: 'Moscow',
    loreZh: '世界上最大的国家。',
    loreEn: 'The largest country in the world.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'italy',
    emoji: '🇮🇹',
    nameZh: '意大利',
    nameEn: 'Italy',
    capitalZh: '罗马',
    capitalEn: 'Rome',
    loreZh: '披萨和面条来自这里。',
    loreEn: 'Birthplace of pizza and pasta.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'spain',
    emoji: '🇪🇸',
    nameZh: '西班牙',
    nameEn: 'Spain',
    capitalZh: '马德里',
    capitalEn: 'Madrid',
    loreZh: '弗拉门戈舞很热情。',
    loreEn: 'Famous for flamenco dancing.',
    rarity: 'common',
    dropWeight: 3,
  },
  {
    slug: 'mexico',
    emoji: '🇲🇽',
    nameZh: '墨西哥',
    nameEn: 'Mexico',
    capitalZh: '墨西哥城',
    capitalEn: 'Mexico City',
    loreZh: '玉米饼和巧克力的故乡。',
    loreEn: 'Birthplace of tacos and chocolate!',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'egypt',
    emoji: '🇪🇬',
    nameZh: '埃及',
    nameEn: 'Egypt',
    capitalZh: '开罗',
    capitalEn: 'Cairo',
    loreZh: '有古老的金字塔。',
    loreEn: 'Home of the ancient pyramids.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'south-africa',
    emoji: '🇿🇦',
    nameZh: '南非',
    nameEn: 'South Africa',
    capitalZh: '比勒陀利亚',
    capitalEn: 'Pretoria',
    loreZh: '可以看到狮子和大象。',
    loreEn: 'Lions and elephants live here.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'argentina',
    emoji: '🇦🇷',
    nameZh: '阿根廷',
    nameEn: 'Argentina',
    capitalZh: '布宜诺斯艾利斯',
    capitalEn: 'Buenos Aires',
    loreZh: '探戈舞很有名。',
    loreEn: 'Famous for the tango dance.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'switzerland',
    emoji: '🇨🇭',
    nameZh: '瑞士',
    nameEn: 'Switzerland',
    capitalZh: '伯尔尼',
    capitalEn: 'Bern',
    loreZh: '巧克力和奶酪很美味。',
    loreEn: 'Famous for chocolate and cheese.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'greece',
    emoji: '🇬🇷',
    nameZh: '希腊',
    nameEn: 'Greece',
    capitalZh: '雅典',
    capitalEn: 'Athens',
    loreZh: '奥林匹克运动会从这里开始。',
    loreEn: 'Where the Olympics began.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'netherlands',
    emoji: '🇳🇱',
    nameZh: '荷兰',
    nameEn: 'Netherlands',
    capitalZh: '阿姆斯特丹',
    capitalEn: 'Amsterdam',
    loreZh: '风车和郁金香很多。',
    loreEn: 'Famous for windmills and tulips.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'thailand',
    emoji: '🇹🇭',
    nameZh: '泰国',
    nameEn: 'Thailand',
    capitalZh: '曼谷',
    capitalEn: 'Bangkok',
    loreZh: '大象和金色寺庙。',
    loreEn: 'Home of elephants and golden temples.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'singapore',
    emoji: '🇸🇬',
    nameZh: '新加坡',
    nameEn: 'Singapore',
    capitalZh: '新加坡',
    capitalEn: 'Singapore',
    loreZh: '小小的花园城市。',
    loreEn: 'The tiny garden city.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'turkey',
    emoji: '🇹🇷',
    nameZh: '土耳其',
    nameEn: 'Türkiye',
    capitalZh: '安卡拉',
    capitalEn: 'Ankara',
    loreZh: '热气球飞过卡帕多奇亚。',
    loreEn: 'Hot air balloons over Cappadocia!',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'saudi-arabia',
    emoji: '🇸🇦',
    nameZh: '沙特阿拉伯',
    nameEn: 'Saudi Arabia',
    capitalZh: '利雅得',
    capitalEn: 'Riyadh',
    loreZh: '沙漠和椰枣的国度。',
    loreEn: 'Land of deserts and date palms.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'uae',
    emoji: '🇦🇪',
    nameZh: '阿联酋',
    nameEn: 'UAE',
    capitalZh: '阿布扎比',
    capitalEn: 'Abu Dhabi',
    loreZh: '世界最高的楼在迪拜。',
    loreEn: 'Has the tallest tower in the world.',
    rarity: 'epic',
    dropWeight: 1,
  },
  {
    slug: 'vietnam',
    emoji: '🇻🇳',
    nameZh: '越南',
    nameEn: 'Vietnam',
    capitalZh: '河内',
    capitalEn: 'Hanoi',
    loreZh: '河粉很好吃。',
    loreEn: 'Famous for pho noodle soup.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'indonesia',
    emoji: '🇮🇩',
    nameZh: '印度尼西亚',
    nameEn: 'Indonesia',
    capitalZh: '雅加达',
    capitalEn: 'Jakarta',
    loreZh: '一千七百个海岛。',
    loreEn: 'Made of 17,000 islands!',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'portugal',
    emoji: '🇵🇹',
    nameZh: '葡萄牙',
    nameEn: 'Portugal',
    capitalZh: '里斯本',
    capitalEn: 'Lisbon',
    loreZh: '蛋挞最早从这里来。',
    loreEn: 'Birthplace of the egg tart.',
    rarity: 'rare',
    dropWeight: 2,
  },
  {
    slug: 'sweden',
    emoji: '🇸🇪',
    nameZh: '瑞典',
    nameEn: 'Sweden',
    capitalZh: '斯德哥尔摩',
    capitalEn: 'Stockholm',
    loreZh: '冬天有北极光。',
    loreEn: 'Northern lights shine in winter.',
    rarity: 'epic',
    dropWeight: 1,
  },
];

export const FLAGS_BY_SLUG: Record<string, FlagItem> = Object.fromEntries(
  FLAGS.map((f) => [f.slug, f]),
);
